<a href="https://colab.research.google.com/github/rrankawat/numpy-basic/blob/main/How_To_Filter_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How To Filter Numpy Arrays - Numpy For Machine Learning 9

In [1]:
import numpy as np

In [3]:
# Filtering Numpy Arrays with Boolean Index Lists
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

x = [True, True, False, False, False, True, False, False, False, False]

print(np1)
print(np1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 6]


In [4]:
filtered = []

for thing in np1:
  if thing % 2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [5]:
# Shorthand!
filtered = np1 % 2 == 0

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [6]:
# gt > 5
filtered = np1 > 5

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
