<a href="https://colab.research.google.com/github/rrankawat/numpy-basic/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro To Numpy - Numpy For Machine Learning 1
[YouTube](https://youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&si=tZHaRo6tj2S2Zr36)

In [14]:
# Basic Python List
list1 = [1, 2, 3, 4, 5]
list1
list1[0]

list2 = ["John Elder", 41, list1, True]
list2

['John Elder', 41, [1, 2, 3, 4, 5], True]

In [13]:
# Numpy - Numeric Python
# data type: ndarray (n dimensional array)

import numpy as np

np1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np1
np1.shape

(10,)

In [15]:
# Arange
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Step
np3 = np.arange(0, 10, 2)
np3

array([0, 2, 4, 6, 8])

In [17]:
# Zeros
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# Multidimensional Zeros
np5 = np.zeros((2, 10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
# Full
np6 = np.full((10), 6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [21]:
# Multidimensional Full
np7 = np.full((2, 10), 6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [24]:
# Convert Python List to np
my_list = [1, 2, 3, 4, 5]
np8 = np.array(my_list)
np8

array([1, 2, 3, 4, 5])