<a href="https://colab.research.google.com/github/rrankawat/numpy-basic/blob/main/Numpy_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Universal Functions - Numpy For Machine Learning 3

In [4]:
import numpy as np

np1 = np.array([-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Square root of each element
np.sqrt(np1)

<ipython-input-4-49ad71c72efb>:6: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np1)


array([       nan,        nan,        nan, 0.        , 1.        ,
       1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        ])

In [5]:
# Absolute value
np.absolute(np1)

array([3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Exponential
np.exp(np1)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [9]:
# Min/Max
np.max(np1)
np.min(np1)

-3

In [10]:
# Sign positive or negative
np.sign(np1)

array([-1, -1, -1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [15]:
# Trigonometry: sin, cos, log

# np.sin(np1)
# np1

# np.cos(np1)
# np1

# np.log(np1)
# np1