<a href="https://colab.research.google.com/github/rrankawat/numpy-basic/blob/main/Searching_Numpy_Arrays_The_Easy_Way.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Searching Numpy Arrays The Easy Way - Numpy For Machine Learning 8

In [2]:
import numpy as np

In [7]:
# Search
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 3, 9, 10, 3])
x = np.where(np1 == 3)

print(x[0])
print(np1[x[0]])

[ 2  8 11]
[3 3 3]


In [9]:
# Return even items
y = np.where(np1 % 2 == 0)

print(y[0])

[ 1  3  5  7 10]


In [11]:
# Return odd items
z = np.where(np1 % 2 == 1)

print(z[0])

[ 0  2  4  6  8  9 11]
