<a href="https://colab.research.google.com/github/rrankawat/numpy-basic/blob/main/Slicing_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Slicing Numpy Arrays - Numpy For Machine Learning 2

In [1]:
import numpy as np

# Slicing Numpy Arrays
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Return 2, 3, 4, 5
np1[1:5]

array([2, 3, 4, 5])

In [2]:
# Return from something till the end of the array?

# Return 4-9
np1[3:]

array([4, 5, 6, 7, 8, 9])

In [3]:
# Return Negative Slices

# 7, 8
np1[-3: -1]

array([7, 8])

In [5]:
# Steps
np1[1:5:2]

array([2, 4])

In [6]:
# Steps on the entire array
np1[::2]

array([1, 3, 5, 7, 9])

In [8]:
# Slice a 2-d array
np2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Pull out a single item
np2[1, 2]

8

In [10]:
# Slice a 2-d array
np2[0:1, 1:3]

array([[2, 3]])

In [11]:
# Slice from both rows
np2[0:2, 1:3]

array([[2, 3],
       [7, 8]])