<a href="https://colab.research.google.com/github/rrankawat/numpy-basic/blob/main/Sorting_Numpy_Arrays_The_Right_Way.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sorting Numpy Arrays The Right Way - Numpy For Machine Learning 7

In [1]:
import numpy as np

In [2]:
# np.sort()
np1 = np.array([6, 7, 9, 0, 2, 1])

print(np.sort(np1))

[0 1 2 6 7 9]


In [4]:
# Alphabtical
np2 = np.array(["John", "Tara", "Aaron", "Zed"])

print(np.sort(np2))

['Aaron' 'John' 'Tara' 'Zed']


In [5]:
# Booleans T/F
np3 = np.array([True, False, False, True])

print(np.sort(np3))

[False False  True  True]


In [6]:
# Return a copy not change the original
print(np1)
print(np.sort(np1))

[6 7 9 0 2 1]
[0 1 2 6 7 9]


In [8]:
# 2-D
np4 = np.array([[6, 7, 1, 9], [8, 3, 5, 0]])

print(np4)
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]
